"""
Pydantic schemas for API request/response validation
"""

from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, List


# ============================================================================
# PR Schemas
# ============================================================================

class PRCreate(BaseModel):
    """Request body for logging a PR"""
    user_id: str
    username: str
    exercise: str
    weight: float = Field(gt=0, description="Weight in lbs")
    reps: int = Field(gt=0, description="Number of reps")
    message_id: str = "dashboard"
    channel_id: str = "dashboard"


class PRResponse(BaseModel):
    """Response for a logged PR"""
    id: int
    user_id: str
    username: str
    exercise: str
    weight: float
    reps: int
    estimated_1rm: float
    timestamp: datetime
    is_new_pr: bool = False  # Calculated by API
    
    class Config:
        from_attributes = True


class BestPRResponse(BaseModel):
    """Response for best PR query"""
    exercise: str
    weight: float
    reps: int
    estimated_1rm: float
    timestamp: datetime
    
    class Config:
        from_attributes = True


# ============================================================================
# Workout Schemas
# ============================================================================

class WorkoutExercise(BaseModel):
    """Single exercise in a workout plan"""
    exercise_order: int
    exercise_name: str
    setup_notes: Optional[str] = None
    video_link: Optional[str] = None
    special_logging: Optional[str] = None  # 'weight_only', 'reps_as_seconds', or None


class WorkoutPlanCreate(BaseModel):
    """Request to create/update a workout plan"""
    user_id: str
    workout_letter: str = Field(pattern="^[A-E]$", description="Workout letter A-E")
    exercises: List[WorkoutExercise]


class WorkoutCompletionUpdate(BaseModel):
    """Request to mark a workout as completed"""
    user_id: str
    workout_letter: str = Field(pattern="^[A-E]$")


class DeloadStatus(BaseModel):
    """Deload counter status for a workout"""
    workout_letter: str
    completion_count: int
    needs_deload: bool = False  # True if >= 6


# ============================================================================
# XP Schemas
# ============================================================================

class XPAward(BaseModel):
    """Request to award XP"""
    user_id: str
    username: str
    xp_amount: int = Field(gt=0, description="XP to award")
    reason: str = "manual"  # "pr", "weekly_log", "core_foods", etc.


class XPResponse(BaseModel):
    """Response with user's XP status"""
    user_id: str
    username: str
    total_xp: int
    level: int
    xp_for_next_level: int
    
    class Config:
        from_attributes = True


# ============================================================================
# Dashboard Member Schemas
# ============================================================================

class DashboardMemberCreate(BaseModel):
    """Request to create a dashboard member"""
    user_id: str
    username: str


class DashboardMemberResponse(BaseModel):
    """Response with dashboard member info"""
    user_id: str
    username: str
    unique_code: str
    dashboard_url: str  # Generated by API
    
    class Config:
        from_attributes = True


# ============================================================================
# Core Foods Schemas
# ============================================================================

class CoreFoodsLog(BaseModel):
    """Request to log core foods"""
    user_id: str
    date: str = Field(description="Date in YYYY-MM-DD format")
    completed: bool = True
